schools = [
    'ABR videregående skole as',
    'Agder Folkehøgskole',
    'Aglo videregående skole',
    'Akademiet Bergen FPG as',
    'Akademiet Heltberg Toppidrettsgymnas Molde',
    'Akademiet Heltberg Toppidrettsgymnas Ålesund',
    'Akademiet Privatistskole',
    'Akademiet VGS Drammen',
    'Akademiet VGS Fredrikstad',
    'Akademiet VGS Kristiansand',
    'Akademiet VGS Molde',
    'Akademiet VGS Oslo',
    'Akademiet VGS Sandnes as',
    'Akademiet VGS Ålesund',
    'Akademiet Ypsilon videregående skole as',
    'Alta videregående skole / Àlttà joatkkaskuvla',
    'Alta videregående skole Yrkessjåfører',
    'Amalie Skram videregående skole',
    'Andøy videregående skole',
    'Ansgar Teologiske Høgskole',
    'Arbeiderbevegelsens Folkehøgskole Ringsaker',
    'Arendal videregående skole Undervisningsted Mølleheia',
    'Arendal videregående skole',
    'Arna vidaregåande skule Avdeling Garnes',
    'Arna vidaregåande skule',
    'Art Complexion makeupskole',
    'Asker Kunstfagskole',
    'Asker videregående skole',
    'Askim videregående skole',
    'Askøy videregående skole',
    'Atlanten videregående skole',
    'Atlantis Medisinske Høgskole',
    'Aust-Lofoten videregående skole',
    'Austevoll vidaregåande skule',
    'Austrheim vidaregåande skule',
    'BI Bank og Forsikring',
    'Bamble videregående skole Avdeling Croftholmen',
    'Bamble videregående skole',
    'Bardufoss videregående skole',
    'Barratt Due musikkinstitutt',
    'Bergeland videregående skole Filial Tanke Svilands gate',
    'Bergeland videregående skole',
    'Bergen Arkitekthøgskole',
    'Bergen Katedralskole',
    'Bergen Private Gymnas',
    'Bergen maritime videregående skole',
    'Beverage Academy Norge',
    'Bilder Nordic School of Photography',
    'Bjerke videregående skole',
    'Bjertnes videregående skole',
    'Bjørkelangen videregående skole',
    'Bjørknes Høyskole',
    'Bjørnholt videregående skole',
    'Bleiker videregående skole',
    'Blindern videregående skole',
    'Bodin videregående skole og maritime fagskole',
    'Bodø videregående skole',
    'Borg videregående skole',
    'Borgund vidaregåande skole',
    'Breivang videregående skole',
    'Briskeby videregående skole as',
    'Bryne vidaregåande skule',
    'Brønnøysund videregående skole',
    'Buskerud Folkehøgskole',
    'Buskerud videregående skole Avdeling Buskerud',
    'Buskerud videregående skole',
    'Bybroen videregående skole',
    'Byremo videregående skole',
    'Byåsen videregående skole',
    'Bårdar Akademiet',
    'Båtsfjord private videregående skole as',
    'Bø vidaregåande skule',
    'Bømlo Folkehøgskule',
    'Bømlo vidaregåande skule',
    'Centric IT Academy',
    'Charlottenlund videregående skole',
    'Chr. Thams fagskole',
    'DTK - Kunstfagskolen i Bærum',
    'Dahlske videregående skole',
    'Dalane videregående skole',
    'Dale vidaregåande skule',
    'Danielsen Intensivgymnas',
    'Danielsen Videregående Skole',
    'Den tysk-norske skolen i Oslo/Deutsch-Norwegische Schule Oslo',
    'Designinstituttet ',
    'Dokka videregående skole',
    'Drammen videregående skole',
    'Dronning Mauds Minne Høgskole',
    'Drottningborg videregående skole',
    'Drømtorp videregående skole',
    'Dønski videregående skole',
    'ESMOD Oslo, Fashion Mode AS ',
    'Edvard Munch videregående skole',
    'Eid vidaregåande skule',
    'Eidsvoll videregående skole',
    'Eikeli videregående skole',
    'Eiker videregående skole',
    'Eilert Sundt videregående skole Studiested Farsund',
    'Eilert Sundt videregående skole Studiested Lista',
    'Eilert Sundt videregående skole Studiested Lyngdal',
    'Eilert Sundt videregående skole',
    'Einar Granum Kunstfagskole',
    'Elvebakken videregående skole',
    'Elverum folkehøgskule',
    'Elverum videregående skole',
    'Emergence School of Leadership',
    'Etterstad videregående skole',
    'European Helicopter Center',
    'Evje Folkehøgskole',
    'Fagerlia videregående skole',
    'Fagskolen Innlandet, Hvam vgs.',
    'Fagskolen Innlandet, Jessheim vgs.',
    'Fagskolen Innlandet, Kjelle vgs.',
    'Fagskolen Innlandet, Nome vgs.',
    'Fagskolen Innlandet, Storsteigen vgs.',
    'Fagskolen Innlandet, Trysil vgs.',
    'Fagskolen Innlandet, Vest-Telemark museum',
    'Fagskolen Innlandet, avd. Bygningsvernsenteret',
    'Fagskolen Innlandet, avd. Gjøvik',
    'Fagskolen Innlandet, avd. Karriere Oppland',
    'Fagskolen Innlandet, avd. Storhamar ',
    'Fagskolen Innlandet, Ål vgs.',
    'Fagskolen Innlandet',
    'Fagskolen Kristiania',
    'Fagskolen Oslo Akershus, Bjørkelangen vgs.',
    'Fagskolen Oslo Akershus, Vestby vgs.',
    'Fagskolen Oslo Akershus, avd. Oslo',
    'Fagskolen Oslo Akershus, avd. Rud vgs.',
    'Fagskolen Oslo Akershus, avd. Strømmen vgs.',
    'Fagskolen Oslo Akershus',
    'Fagskolen Rogaland, avd. Karmsund',
    'Fagskolen Rogaland, avd. Møllehagen',
    'Fagskolen Rogaland, avd. SOTS',
    'Fagskolen Telemark',
    'Fagskolen Tinius Olsen',
    'Fagskolen for bokbransjen',
    'Fagskolen i Hordaland, Austevoll',
    'Fagskolen i Hordaland, Hjeltnes',
    'Fagskolen i Hordaland, Nedre Nygård',
    'Fagskolen i Hordaland, avd. Nordnes',
    'Fagskolen i Hordaland, avd. Voss',
    'Fagskolen i Hordaland',
    'Fagskolen i Kirkenes',
    'Fagskolen i Kristiansand',
    'Fagskolen i Kristiansund',
    'Fagskolen i Troms, avd. Harstad',
    'Fagskolen i Troms, avd. Nord-Troms',
    'Fagskolen i Troms, avd. Tromsø, helse',
    'Fagskolen i Troms, avd. Tromsø, maritime',
    'Fagskolen i Troms, avd. Tromsø, teknisk',
    'Fagskolen i Vestfold, Horten',
    'Fagskolen i Ålesund',
    'Fagskolen i Østfold',
    'Fagskulen i Sogn og Fjordane, avd. Førde',
    'Fagskulen i Sogn og Fjordane, maritim avd. Måløy',
    'Fana folkehøgskule',
    'Fannefjord videregående skole',
    'Fauske videregående skole',
    'Firda vidaregåande skule',
    'Fitjar vidaregåande skule',
    'Fjellhaug Internasjonale Høgskole',
    'Fjordane Folkehøgskule',
    'Flekkefjord videregående skole Studiested Flekkefjord',
    'Flekkefjord videregående skole Studiested Kvinesdal',
    'Flekkefjord videregående skole',
    'Flora vidaregåande skule',
    'Follo Folkehøgskole',
    'Forsvarets høgskole',
    'Fosen folkehøgskole',
    'Fosen videregående skole',
    'Foss videregående skole',
    'Framnes kristne vidaregåande skule',
    'Frederik II videregående skole',
    'Fredrikstad og Oslo FagAkademi',
    'Frelsesarmeens offiserskole',
    'Frogn videregående skole',
    'Fræna vidaregåande skole',
    'Fusa vidaregåande skule',
    'Fyllingsdalen videregående skole',
    'Fyrstikkalleen skole',
    'Færder videregående skole',
    'Gand videregående skole',
    'Gauldal fagskole',
    'Gauldal videregående skole',
    'Gausdal videregående skole',
    'Gjennestad videregående skole',
    'Gjermundnes vidaregåande skule',
    'Gjøvik videregående skole',
    'Glemmen videregående skole Avdeling Lillebekk',
    'Glemmen videregående skole Avdeling Lisleby',
    'Glemmen videregående skole',
    'Godalen videregående skole',
    'Gol vidaregåande skule',
    'Greveskogen videregående skole',
    'Greåker videregående skole',
    'Grong videregående skole',
    'Guri Kunna videregående skole Skolested Frøya',
    'Guri Kunna videregående skole Skolested Hitra',
    'Guri Kunna videregående skole',
    'Hadeland folkehøgskole',
    'Hadeland videregående skole',
    'Hadsel fagskole',
    'Hadsel videregående skole',
    'Hafstad vidaregåande skule',
    'Hald Internasjonale Senter',
    'Halden videregående skole Studiested Porsnes',
    'Halden videregående skole Studiested Risum',
    'Halden videregående skole Tosterødberget',
    'Halden videregående skole',
    'Hallingdal Folkehøgskule',
    'Hamar katedralskole',
    'Hammerfest videregående skole / Hámmerfeasta joatkkaskuvla',
    'Handverksskolen',
    'Hans Nielsen Hauge videregående skole',
    'Haram vidaregåande skule',
    'Hardanger Folkehøgskule',
    'Harstad Folkehøgskole',
    'Hartvig Nissens skole',
    'Haugaland videregående skole',
    'Haugesund Toppidrettsgymnas',
    'Havbruksakademiet videregående skole',
    'Heggen videregående skole',
    'Heimdal videregående skole',
    'Hellerud videregående skole',
    'Helsepedagogisk Steinerskole på Hedemarken',
    'Heltberg Private Gymnas Bislett',
    'Heltberg Private Gymnas Drammen',
    'Heltberg Private Gymnas Ullevaal',
    'Hemne videregående skole',
    'Hersleb videregående skole',
    'Herøy vidaregåande skule Avdeling Vanylven',
    'Herøy vidaregåande skule',
    'Hetland videregående skole',
    'Hjalmar Johansen videregående skole',
    'Holmen skole Videregående',
    'Holmestrand videregående skole',
    'Holtet videregående skole',
    'Hop videregående skole as',
    'Hoppensprett VGS Jessheim as',
    'Horten videregående skole Avdeling Skippergata',
    'Horten videregående skole',
    'Hvam videregående skole',
    'Høgskolen i Innlandet',
    'Høgskolen i Østfold',
    'Høgskulen for landbruk og bygdeutvikling',
    'Høgskulen i Volda',
    'Høgskulen på Vestlandet',
    'Hønefoss videregående skole Filial Risesletta',
    'Hønefoss videregående skole',
    'Høyanger vidaregåande skule',
    'Høyskolen Kristiania ',
    'Høyskolen for dansekunst',
    'Høyskolen for ledelse og teologi',
    'Idrettsskolen Numedal Folkehøgskole',
    'Imageakademiet',
    'Inderøy videregående skole',
    'Institutt for helhetsmedisin',
    'International School of Stavanger',
    'International Stunt Academy',
    'Ishavsbyen videregående skole Skolested Breivika',
    'Ishavsbyen videregående skole Skolested Rambergan',
    'Ishavsbyen videregående skole',
    'Jessheim videregående skole',
    'Jåttå videregående skole',
    'Jæren folkehøgskule',
    'Jønsberg videregående skole',
    'KVS-Bygland',
    'KVS-Lyngdal as',
    'Kalnes videregående skole',
    'Karmsund videregående skole',
    'Karmøy Folkehøgskule  ',
    'Kirkenes videregående skole/Girkonjárgga joatkkaskuvla',
    'Kirkeparken videregående skole',
    'Kjelle videregående skole',
    'Knarvik vidaregåande skule Avdeling Juvikstølen',
    'Knarvik vidaregåande skule',
    'Knut Hamsun videregående skole/Knut Hamsun Joarkkaskåvllå Avdeling Steigen',
    'Knut Hamsun videregående skole/Knut Hamsun Joarkkaskåvllå',
    'Kolon',
    'Kongsbakken videregående skole',
    'Kongsberg videregående skole Undervisningssted Flåtaløkka',
    'Kongsberg videregående skole Undervisningssted Kongsgårdsmoen',
    'Kongsberg videregående skole Undervisningssted Maren Handler',
    'Kongsberg videregående skole Undervisningssted Maurits Hansen',
    'Kongsberg videregående skole Undervisningssted Saggrenda',
    'Kongsberg videregående skole Undervisningssted Tinius Olsen',
    'Kongsberg videregående skole Undervisningssted Åslandsgate',
    'Kongsberg videregående skole',
    'Kongshaug Musikkgymnas',
    'Kongshavn videregående skole',
    'Kopervik videregående skole',
    'Kragerø videregående skole',
    'Kriminalomsorgens høgskole og utdanningssenter KRUS',
    'Kristelig Gymnasium',
    'Kristen VGS Vennesla',
    'Kristen Videregående skole Trøndelag',
    'Kristen videregående skole Haugalandet as',
    'Kristen videregående skole Nordland',
    'Kristiansand katedralskole Gimle',
    'Kristiansund videregående skole',
    'Krokeide videregående skole',
    'Kuben videregående skole',
    'Kunstskolen i Bergen',
    'Kunstskolen i Rogaland',
    'Kvadraturen Skolesenter',
    'Kvaløya videregående skole',
    'Kvam vidaregåande skule Avdeling Norheimsund',
    'Kvam vidaregåande skule Avdeling Øystese',
    'Kvam vidaregåande skule',
    'Kvinnherad vidaregåande skule',
    'Kvitsund Gymnas',
    'Lakselv videregående skole/Leavnnja joatkkaskuvla',
    'Laksevåg videregående skole',
    'Lambertseter videregående skole',
    'Langhaugen videregående skole',
    'Leksvik videregående skole',
    'Lena-Valle videregående skole Avdeling Lena',
    'Lena-Valle videregående skole Avdeling Valle',
    'Lena-Valle videregående skole',
    'Levanger fagskole',
    'Levanger videregående skole',
    'Lier videregående skole',
    'Lillehammer videregående skole Avdeling Nord',
    'Lillehammer videregående skole Avdeling Sør',
    'Lillehammer videregående skole',
    'Lillestrøm videregående skole',
    'Ljabruskolen – Steinerskole for elever med spesielle behov',
    'Lofoten folkehøgskole',
    'Lofoten reiselivfagskole, avd. Stjørdal',
    'Longyearbyen skole, videregående avdeling',
    'Lovisenberg diakonale høgskole',
    'Luftfartsskolen',
    'Luftforsvarets flygeskole',
    'Lukas fagskole og kurssenter',
    'Lukas videregående skole',
    'Lundeneset VGS',
    'Lørenskog videregående skole',
    'Mailand videregående skole',
    'Malakoff videregående skole',
    'Malvik videregående skole',
    'Mandal videregående skole',
    'Manger Folkehøgskule',
    'Meldal videregående skole',
    'Melhus videregående skole',
    'Melsom videregående skole',
    'Meløy videregående skole',
    'Meråker videregående skole',
    'Metis videregående as',
    'Midt-Østerdal videregående skole Nordstumoen',
    'Midt-Østerdal videregående skole',
    'Mo og Øyrane vidaregåande skule Avdeling Mo',
    'Mo og Øyrane vidaregåande skule',
    'Molde videregående skole',
    'Momo Waldorfskole as',
    'Mosjøen videregående skole Hattfjelldal',
    'Mosjøen videregående skole',
    'Moss videregående steinerskole',
    'Musikkteaterhøyskolen',
    'Mysen videregående skole',
    'Måløy vidaregåande skule',
    'Mære landbruksskole',
    'Møglestu videregående skole',
    'Møre Folkehøgskule',
    'NLA Høgskolen',
    'NMBU - Norges miljø- og biovitenskapelige universitet',
    'NORTRAIN - Norwegian Drilling Academy AS',
    'NSKI Høyskole',
    'NTNU Norges teknisk-naturvitenskapelige universitet',
    'NTNU VIDERE',
    'Nadderud videregående skole',
    'Namdals folkehøgskole',
    'Nannestad videregående skole',
    'Nansenskolen',
    'Narvik videregående skole og fagskole',
    'Nasjonal kompetansetjeneste for aldring og helse ',
    'Natur videregående skole',
    'Nes videregående skole',
    'Nesbru videregående skole',
    'Nesodden videregående skole',
    'Nestor',
    'Nome videregåande skole Avdeling Lunde',
    'Nome videregående skole',
    'Nord universitet',
    'Nord-Gudbrandsdal vidaregåande skule avdeling Dombås',
    'Nord-Gudbrandsdal vidaregåande skule avdeling Lom',
    'Nord-Gudbrandsdal vidaregåande skule avdeling Otta',
    'Nord-Gudbrandsdal vidaregåande skule',
    'Nord-Troms videregående skole Avdeling Nordreisa',
    'Nord-Troms videregående skole Avdeling Skjervøy',
    'Nord-Troms videregående skole',
    'Nord-Østerdal videregående skole',
    'Nordahl Grieg videregående skole',
    'Nordborg skoler as Videregående skole',
    'Nordiska Folkhögskolan',
    'Nordkapp maritime fagskole',
    'Nordkapp videregående skole Avdeling Båtsfjord',
    'Nordkapp videregående skole – LOSA Alta',
    'Nordkapp videregående skole – LOSA Berlevåg',
    'Nordkapp videregående skole – LOSA Gamvik',
    'Nordkapp videregående skole – LOSA Hasvik',
    'Nordkapp videregående skole – LOSA Lebesby',
    'Nordkapp videregående skole – LOSA Loppa',
    'Nordkapp videregående skole – LOSA Måsøy',
    'Nordkapp videregående skole – LOSA Tana',
    'Nordkapp videregående skole',
    'Nordkjosbotn videregående skole',
    'Nordland fagskole, Bodø maritime',
    'Nordland fagskole, Lofoten maritime ',
    'Nordland fagskole, helse, sosial og oppvekst',
    'Nordland fagskole, reiseliv',
    'Nordland kunst- og filmfagskole',
    'Nordmøre Folkehøgskule',
    'Nordnorsk Pensjonistskole',
    'Norges Dansehøyskole',
    'Norges Interiørskole',
    'Norges Realfagsgymnas Bærum as (NRG)',
    'Norges Toppidrettsgymnas Bodø',
    'Norges Toppidrettsgymnas Bærum',
    'Norges Toppidrettsgymnas Geilo',
    'Norges Toppidrettsgymnas Kongsvinger as',
    'Norges Toppidrettsgymnas Lillehammer as',
    'Norges Toppidrettsgymnas Tromsø as',
    'Norges grønne fagskole – Vea (Videregående trinn)',
    'Norges grønne fagskole – Vea',
    'Noroff - School of technology and digital media',
    'Norsk Fotofagskole',
    'Norsk Gestaltinstitutt Høyskole',
    'Norsk Hestesenter',
    'Norsk Restaurantskole',
    'Norsk barnebokinstitutt',
    'Norsk fagskole for lokomotivførere',
    'Notodden videregående skole',
    'Numedal videregående skole',
    'Nydalen videregående skole',
    'Nøtterøy videregående skole',
    'OPG Oslo Private Gymnasium',
    'Odda vidaregåande skule',
    'Olav Duun videregående skole',
    'Ole Vig videregående skole',
    'Olsvikåsen videregående skole',
    'Oppdal videregående skole',
    'Orkdal vidaregåande skole',
    'Os gymnas',
    'Os vidaregåande skule',
    'Oslo Handelsgymnasium',
    'Oslo by Steinerskole',
    'Oslo katedralskole',
    'OsloMet – storbyuniversitetet (tidligere Høgskolen i Oslo og Akershus)',
    'Osterøy vidaregåande skule',
    'Otto Treider Private Gymnas',
    'Pasvik Folkehøgskole',
    'Peder Morset folkehøgskole',
    'Persbråten videregående skole',
    'Pilot Flight Academy',
    'Plus-skolen as',
    'Polarsirkelen videregående skole',
    'Politihøgskolen',
    'Porsgrunn videregående skole Avdeling nord',
    'Porsgrunn videregående skole Avdeling sør',
    'Porsgrunn videregående skole',
    'Randaberg videregående skole',
    'Raufoss videregående skole',
    'Rauma videregående skole',
    'Re videregående skole',
    'Ringebu Folkehøgskule',
    'Ringerike Folkehøgskole',
    'Ringerike videregående skole',
    'Ringsaker videregående skole Avdeling Moelv',
    'Ringsaker videregående skole',
    'Rissa videregående skole',
    'Risør videregående skole',
    'Rjukan videregående skole',
    'Roald Amundsen videregående skole',
    'Rogaland Kurs og Kompetansesenter',
    'Romerike Folkehøgskole',
    'Romsdal videregående skole',
    'Rosenvilde videregående skole',
    'Rubbestadnes vidaregåande skule',
    'Rud videregående skole',
    'Rudolf Steinerskolen i Bergen',
    'Rå videregående skole',
    'Rælingen videregående skole',
    'Røros videregående skole',
    'Røyken videregående skole',
    'SKAP Kreativ Folkehøyskole',
    'Saltdal videregående skole',
    'Sam Eyde videregående skole',
    'Sami joatkkaskuvla ja boazodoalloskuvla / Samisk videregående og reindriftsskole',
    'Samisk videregående skole Karasjok – Sámi joatkkaskuvla Kárásjogas',
    'Sande videregående skole',
    'Sandefjord videregående skole',
    'Sandnes videregående skole',
    'Sandnessjøen videregående skole',
    'Sandsli videregående skole',
    'Sandvika videregående skole',
    'Sauda vidaregåande skule Avdeling Sand',
    'Sauda vidaregåande skule',
    'Seiersborg videregående skole as',
    'Selbu videregående skole',
    'Seljord Folkehøgskule',
    'Senja videregående skole Avdeling Finnfjordbotn',
    'Senja videregående skole Avdeling Gibostad',
    'Senja videregående skole',
    'Sentrum videregående skole',
    'Setesdal Folkehøgskule',
    'Setesdal vidaregåande skule Avdeling Hornnes',
    'Setesdal vidaregåande skule Avdeling Hovden',
    'Setesdal vidaregåande skule Avdeling Valle',
    'Setesdal vidaregåande skule',
    'Signo grunn- og videregående skole as',
    'Sirdal videregående skole',
    'Sjøvegan videregående skole',
    'Skagerak International School',
    'Skarnes videregående skole',
    'Skedsmo videregående skole',
    'Skeisvang videregående skole',
    'Ski videregående skole',
    'Skien videregående skole',
    'Skiringssal folkehøyskole',
    'Skjeberg Folkehøyskole',
    'Skjetlein videregående skole',
    'Skogmo videregående skole',
    'Skogn folkehøgskole',
    'Skoleskipet Gann',
    'Skrivekunstakademiet i Hordaland',
    'Slottsfjellet videregående steinerskole',
    'Slåtthaug videregående skole',
    'SoFI - School of Fashion Industry',
    'Sogn Jord- og Hagebruksskule',
    'Sogndal folkehøgskule',
    'Sogndal vidaregåande skule',
    'Sola videregående skole',
    'Solbakken folkehøgskole',
    'Solør videregående skole Studiested Sønsterud',
    'Solør videregående skole Studiested Våler',
    'Solør videregående skole',
    'Sonans Utdanning',
    'Sortland videregående skole Filial Kleiva',
    'Sortland videregående skole Filial Øksnes',
    'Sortland videregående skole',
    'Sotra vidaregåande skule Avdeling Sund',
    'Sotra vidaregåande skule',
    'Spjelkavik videregående skole',
    'St. Hallvard videregående skole',
    'St. Olav videregående skole',
    'St. Paul gymnas',
    'St. Svithun videregående skole',
    'Stabekk videregående skole',
    'Stange videregående skole',
    'Stangnes videregående skole',
    'Stavanger katedralskole Bjergsted',
    'Stavanger katedralskole',
    'Stavanger offshore tekniske skole',
    'Steinerhøyskolen',
    'Steinerskolen i Stavanger',
    'Steinerskolen i Trondheim (Skansen Videregående Steinerskole)',
    'Steinerskolen på Hedemarken',
    'Steinkjer fagskole',
    'Steinkjer videregående skole',
    'Stend vidaregåande skule',
    'Stiftelsen Sørlandets maritime videregående skole',
    'Stiftelsen Telemark Toppidrett Gymnas',
    'Stiftelsen Østerbo videregående skole',
    'Stjørdal fagskole, studiested Fauske',
    'Stjørdal fagskole, studiested Namsos',
    'Stjørdal fagskole, studiested Stjørdal',
    'Stord vidaregåande skule Avdeling Saghaugen',
    'Stord vidaregåande skule Avdeling Vabakkjen',
    'Stord vidaregåande skule',
    'Storhamar videregående skole',
    'Storsteigen videregående skole',
    'Stovner videregående skole',
    'Strand videregående skole',
    'Stranda vidaregåande skule',
    'Strinda videregående skole',
    'Stryn vidaregåande skule',
    'Strømmen videregående skole',
    'Sund folkehøgskole',
    'Sunndal vidaregåande skole',
    'Sunnhordland folkehøgskule',
    'Surnadal vidaregåande skole',
    'Sygna vidaregåande skule',
    'Sykkylven vidaregåande skule',
    'Sámi allaskuvla / Samisk høgskole/ Sámi University College',
    'Søgne videregående skole',
    'Sørlandets fagskole',
    'Sørumsand videregående skole',
    'TISIP',
    'Tana videregående skole / Deanu joatkkaskuvla',
    'Tangen videregående skole',
    'Tertnes videregående skole',
    'Thor Heyerdahl videregående skole',
    'Thora Storm videregående skole',
    'Tiller videregående skole',
    'Tingvoll vidaregåande skole',
    'Tomb videregående skole',
    'Tone Lise Akademiet ',
    'Toneheim Folkehøgskole',
    'Torshus folkehøgskule',
    'Toten Folkehøgskole',
    'Treider Fagskoler',
    'Tromsdalen videregående skole',
    'Trondheim Fagskole',
    'Trondheim katedralskole',
    'Tryggheim Forus videregående skole',
    'Tryggheim vidaregåande skule',
    'Trysil videregående skole',
    'Trøndertun folkehøgskole',
    'Tunsberg Medisinske Skole ',
    'Tvedestrand og Åmli videregående skole Avdeling Holt',
    'Tvedestrand og Åmli videregående skole Avdeling Tvedestrand',
    'Tvedestrand og Åmli videregående skole Avdeling Åmli',
    'Tvedestrand og Åmli videregående skole',
    'Tveit vidaregåande skule',
    'Tyrifjord videregående skole',
    'Tøndergård skole og ressurssenter',
    'UWC United World College',
    'UiT Norges arktiske universitet',
    'Ullern videregående skole',
    'Ulsrud videregående skole',
    'Ulstein vidaregåande skule',
    'Universitetet i Agder',
    'Universitetet i Bergen',
    'Universitetet i Oslo',
    'Universitetet i Stavanger, Etter- og videreutdanning',
    'Universitetet i Stavanger',
    'Universitetet i Sørøst-Norge',
    'Vadsø videregående skole / Cáhcesullo joatkkaskuvla',
    'Val videregående skole as',
    'Valdres vidaregåande skule',
    'Valle Hovin videregående skole',
    'Valler videregående skole',
    'Vardafjell videregående skole',
    'Vardø videregående skole/Várggáidt joatkkaskuvla',
    'Vefsn Folkehøgskole - Toppen',
    'Vennesla videregående skole',
    'Verdal videregående skole',
    'Vest-Lofoten videregående skole / Lofoten maritime fagskole',
    'Vest-Telemark vidaregåande skule Avdeling Seljord',
    'Vest-Telemark vidaregåande skule',
    'Vestborg vidaregåande skule',
    'Vestby videregående skole',
    'Vinstra vidaregåande skule',
    'Vinterlandbruksskulen i Ryfylke',
    'Vinterlandbruksskulen på Jæren',
    'Volda vidaregåande skule',
    'Voss folkehøgskule',
    'Voss gymnas',
    'Voss vidaregåande skule',
    'Vågen videregående skole',
    'Vågsbygd videregående skole',
    'WANG Toppidrett Fredrikstad',
    'WANG videregående/WANG Toppidrett',
    'Wang Toppidrett Hamar as',
    'Wang Toppidrett Stavanger AS',
    'Wang Toppidrett Tønsberg as',
    'Ytre Namdal Fagskole',
    'Ytre Namdal videregående skole',
    'Åfjord videregående skole',
    'Åkrehamn vidaregåande skole',
    'Ål Folkehøyskole og kurssenter for døve',
    'Ål vidaregåande skole',
    'Ålesund kunstfagskole',
    'Ålesund videregående skole',
    'Årdal vidaregåande skule',
    'Årstad videregående skole',
    'Ås videregående skole',
    'Åsane folkehøgskole - Bergen',
    'Åsane videregående skole Avdeling Eidsvåg',
    'Åsane videregående skole',
    'Åssiden videregående skole',
    'Øksnevad vidaregåande skole',
    'Ølen vidaregåande skule',
    'Ørsta vidaregåande skule',
    'Østfold Møbelsnekkerskole',
    'Øvrebyen videregående skole',
    'Øvrebø videregående skole as',
    'Øya videregående skole',
]
