module.exports = {
    TY: 'Type of reference (must be the first tag)',
    ID: 'Identification number for the reference. Not an official field',
    Y1: 'Year of publication. Not an official field',
    A1: 'First Author (each author on its own line preceded by the tag)',
    A2: 'Secondary Author (each author on its own line preceded by the tag)',
    A3: 'Tertiary Author (each author on its own line preceded by the tag)',
    A4: 'Subsidiary Author (each author on its own line preceded by the tag)',
    AB: 'Abstract',
    AD: 'Author Address',
    AN: 'Accession Number',
    AU: 'Author (each author on its own line preceded by the tag)',
    C1: 'Custom 1',
    C2: 'Custom 2',
    C3: 'Custom 3',
    C4: 'Custom 4',
    C5: 'Custom 5',
    C6: 'Custom 6',
    C7: 'Custom 7',
    C8: 'Custom 8',
    CA: 'Caption',
    CN: 'Call Number',
    CY: 'Place Published',
    DA: 'Date',
    DB: 'Name of Database',
    DO: 'DOI',
    DP: 'Database Provider',
    EP: 'End Page',
    ET: 'Edition',
    IS: 'Number ',
    J2: 'Alternate Title (this field is used for the abbreviated title of a book or journal name)',
    KW: 'Keywords (keywords should be entered each on its own line preceded by the tag)',
    L1: 'File Attachments (this is a link to a local file on the users system not a URL link)',
    L4: 'Figure (this is also meant to be a link to a local file on the users\'s system and not a URL link)',
    LA: 'Language',
    LB: 'Label',
    M1: 'Number',
    M3: 'Type of Work',
    N1: 'Notes',
    NV: 'Number of Volumes',
    OP: 'Original Publication',
    PB: 'Publisher',
    PY: 'Year',
    RI: 'Reviewed Item',
    RN: 'Research Notes',
    RP: 'Reprint Edition',
    SE: 'Section',
    SN: 'ISBN/ISSN',
    SP: 'Start Page',
    ST: 'Short Title',
    T1: 'Primary Title',
    T2: 'Secondary Title',
    T3: 'Tertiary Title',
    TA: 'Translated Author',
    TI: 'Title',
    TT: 'Translated Title',
    UR: 'URL',
    VL: 'Volume',
    Y2: 'Access Date',
    ER: 'End of Reference (must be the last tag)'
};
